Messages:
- 'First Line'
- '&aComing Soon!'
- '&6Pet'
- '&6 '
- '&a%on/%maxp'
- '&6Online Players'
- '&4 '
- '&a%tokens'
- '&6Tokens'
- '&1 '
- '&a - Factions'
- '&dCommon Servers'
- '&1 '
- '&aSky Warz'
- '&aChickenShoot '
- '&aKitPvP'
Title: '&5&lPortal &6&lKings'
